###  ImageOnMap configuration file


# Plugin language. Empty: system language.
# Available: en-US (default, fallback), fr-FR, ru-RU, de-DE, zh-CN, ja-JP, es-ES.
lang: en-US

#if true, in addition to checking the local 'BannedImageHashes' file, 
#the plugin will also ping the user's image hash off to the API to be checked with the remote database
#if false, the plugin will only check the local 'BannedImageHashes' file.
ENABLE_API: false

#API used for checking hashes, must support HEX hashes, 
#return "{"banned":false,"reason":null}" when a hash is not banned, 
#and "{"banned":true,"reason":"reason string"}" when banned
API: ""

PERMPDQBAN: "You have been permanently banned from mc.soyjak.party for the following reason:\n\n%REASON%\n\nYour ban was filed on %TIME% and will NOT expire.\n\nAccording to our server, your IP is: %IP%. The name you were posting with \nwas %NAME%.\n\n"

PDQBAN: "You have been banned from mc.soyjak.party for the following reason:\n\n%REASON%\n\nYour ban was filed on %TIME% and expires on %EXPIRES% from now.\n\nAccording to our server, your IP is: %IP%. The name you were posting with \nwas %NAME%."

# Allows collection of anonymous statistics on plugin environment and usage
# The statistics are publicly visible here: http://mcstats.org/plugin/ImageOnMap
collect-data: true


# Images rendered on maps consume Minecraft maps ID, and there are only 32 767 of them.
# You can limit the maximum number of maps a player, or the whole server, can use with ImageOnMap.
# 0 means unlimited.
map-global-limit: 0
map-player-limit: 0


# Maximum size in pixels for an image to be. 0 is unlimited.
limit-map-size-x: 0
limit-map-size-y: 0


# Should the full image be saved when a map is rendered?
save-full-image: false

